name:                latex-svg
version:             0.1.0.0
github:              "poscat0x04/latex-svg"
license:             BSD3
author:              "Poscat"
maintainer:          "poscat@mail.poscat.moe"
copyright:           "2020 Poscat"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/poscat0x04/latex-svg#readme>

dependencies:
- base >= 4.7 && < 5
- svg-tree
- xml
- filepath
- pandoc-types >= 1.19
- directory
- process
- text
- data-default
- bytestring
- lrucache

library:
  source-dirs: src

executables:
  latex-svg-filter:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - latex-svg
